#!/bin/bash
BATF(){
AWKBAT='
	{
	    gsub(/,|%/,"")
	    if ($3 == "Charging") {
		print "" " " $4"%"
	    } else if ($4 <= 15) {
		print "" " " $4"%"
	    } else if ($4 <= 25) {
		print "" " " $4"%"
	    } else if ($4 <= 50) {
		print "" " " $4"%"
	    } else if ($4 <= 75) {
		print "" " " $4"%"
	    } else {
		print "" " " $4"%"
	    }
	}'

	BAT=$(acpi | awk "$AWKBAT")

	if [[ -n $BAT ]]; then
		echo $BAT
	else
		echo ?
	fi
}

VOLF() {

	AMIXEROUT=$(amixer get Master | grep -m 1 "[0-9]*%")

	VOL=$(echo $AMIXEROUT | grep -o -m 1 "[0-9]*%"| tr -d "%")

	STATUS=$(echo $AMIXEROUT | grep -o -m 1 "off")

	if [ $VOL -eq 0 ] || [ -n "$STATUS" ]; then
		#muted
		echo muted $VOL%
	elif [[ $VOL -le 33 ]]; then
		#statements
		echo  $VOL%
	elif [[ $VOL -le 66 ]]; then
		#statements
		echo  $VOL%
	elif [[ $VOL -le 100 ]]; then
		#statements
		echo  $VOL%
	fi
}

SPTY() {

	#adapted from: https://github.com/getmicah/spotify-now
	status=`pidof spotify | wc -l`
	if [[ "$status" != 1 ]]; then
		exit 1
	fi

	PLAYBACK=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus' | grep -o Paused`
	if [[ "$PLAYBACK" == "Paused" ]]; then
		echo ' Song paused'
		exit 1
	fi

	META=`dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`

	ARTIST=$(echo "$META" | grep -m 1 "xesam:artist" -b2 | tail -n1)
	ARTIST="${ARTIST%\"*}"
	ARTIST="${ARTIST#*\"}"

	TITLE=$(echo "$META" | grep -m 1 "xesam:title" -b1 | tail -n1)
	TITLE="${TITLE%\"*}"
	TITLE="${TITLE#*\"}"

	echo " $ARTIST - $TITLE"
}

pidOfDwmStatus=$(pidof dwmstatusbar)

if [[ "$pidOfDwmStatus" ]]; then
    kill $pidOfDwmStatus
fi

while [[ true ]]; do
    DATE=$(date +"%a %d %b %H:%M")
    BAT=$(BATF)
    VOL=$(VOLF)
    SPOTIFY=$(SPTY)

    xsetroot -name "$SPOTIFY $VOL $BAT $DATE"
    sleep 1
done &
